### ISSUE TITLE
why /collections is overloaded with search capabilities?

### ISSUE THREAD

**Issue by ccancellieri** [stac-api-extensions/collection-search#17]
Hi,
 I'm trying to have a full implementation of a stac catalog also shipping the collection-search.

Unfortunately the implementation encountered a problem:
/collections endpoint is overloaded by this specification as it is taken by the POST PUT endpoint needed to create a collection.

Why don't we define a /collections-search or overload the existing /search endpoint?
Having several functionalities over the same rest path looks quite complex to implement don't you think it would be better to declare a separate endpoint like the one made for item search?

Discussed:
https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/pull/298
https://github.com/stac-utils/stac-fastapi/issues/749

**Comment by m-mohr** [comment]
First of all, this is based on OGC APIs and you'd probably also need to ask them.

But what is the actual issue here? The endpoint already allows basic search and so adding more advanced options seems very logical to me. 

There's no plan for PUT/POST in this extension at this point so there's no conflict with Transactions right now.

**Comment by ccancellieri** [comment]
Thanks for your point of view, noted.
As already mentioned in the above references, this extension is not very useful as it is, so I will go on discussing this at OGC level since you are not available to discuss it here.

**Comment by m-mohr** [comment]
It is useful to various entities already. Honestly I haven't understood yet what the issue is that you are encountering and why it is not useful as it is.

Again: POST is not defined in this extension. POST is a proprietary extension by stac-fastapi!

I'm also not sure what you want to define at OGC level. OGC also doesn't define POST, so they'll likely tell you that POST is not defined and it's not an issue. Please let me know if you open any issues, I'd like to follow them.
