### ISSUE TITLE
conformance versus requirement classes

### ISSUE THREAD

**Issue by ycespb** [stac-api-extensions/collection-search#9]
The current description refers to the following which are called as "conformance classes" but use URI of "requirement classes" ending with /req/:

- (1) http://www.opengis.net/spec/ogcapi-records-1/1.0/req/cql-filter
- (2) http://www.opengis.net/spec/ogcapi-records-1/1.0/req/sorting

Current extension and  https://docs.ogc.org/DRAFTS/20-004.html#_core. should reference (OGC) conformance classes with identifiers ending with /conf/ instead of /req/ ?

Same question/remark for the reference to http://www.opengis.net/spec/ogcapi-common-2/1.0/req/simple-query versus  http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query (which exists in https://docs.ogc.org/DRAFTS/20-024.html#_conformance_class_simple_query).

**Comment by m-mohr** [comment]
Yeah, sorry, that is probably my lack of understanding what the difference is, especially as e.g. they list http://www.opengis.net/spec/ogcapi-records-1/1.0/req/cql-filter alongside conformance classes, too.

Is https://github.com/stac-api-extensions/collection-search/commit/d8e28898a743f7b405d8f99c780e501603c1a065 better?
I made it so that I only list the required STAC conformance classes for the extension and just link to the document. STAC tooling only needs the STAC conformance classes and other can then check the Records documentation for whatever they may want to add in addition. I've updated the conformance classes for simple query, that was easier to figure out.

So please update your implementation accordingly, I'll also do in STAC Browser.

**Comment by ycespb** [comment]
Looks good.  Indeed, also in API-Records, the use of /req/cql-filter seems not consistent... I opened a ticket at https://github.com/opengeospatial/ogcapi-records/issues/284. In the meanwhile, we updated the URI to "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/simple-query"  in our implementation.
